[[projects]]
id = 1
title = "Portfolio"
description = "Proste portfolio napisane w Rust z u≈ºyciem TailwindCSS"
image = "/.perseus/static/img/project.jpg"
tags = ["Rust", "Sycamore", "Perseus"]
github = "https://github.com/kmilczynski/portfolio"
demo = "https://kmilczynski.byst.re/"
